server:
  port: 8081

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:p6spy:mysql://114.55.58.31:3306/shop?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&rewriteBatchedStatements=true
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  servlet:
    multipart:
      max-file-size: -1 #单个上传文件大小无限制
      max-request-size: -1 #单次上传文件大小无限制
  redis:
    host: 114.55.58.31
    port: 6379
    password: 1595904478
  devtools:
    restart:
      enabled: true # 热部署

#返回值,参数类型别名
#mapper存放位置：resources目录下mapper目录

mybatis-plus:
  type-aliases-package: com.share.pojo
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1 #逻辑删除字段值
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.share.pojo.mapper : debug
#    root: debug


minio:
  endpoint: 114.55.58.31
  port: 9000
  accessKey: minioadmin
  secretKey: minioadmin
  secure: false #如果是true，则用的是https而不是http,默认值是true
  bucketName: "shop"
  configDir: "/usr/local/minio/data/"

# 百度官网创建应用后获取
idcard:
  url: "https://aip.baidubce.com/rest/2.0/ocr/v1/idcard"
  clientId: "QpHPdCt5sUkYM5T1X2GGfild"
  clientSecret: "5w4jgpGl2eXoOf8KaGIrZWLj7Q2Kpyb7"


phonecode:
  apiUrl: "https://sms_developer.zhenzikj.com" #接口地址
  appId: "108957" #应用id
  appSecret: "80ff03e7-76b0-46d6-b064-4491ba404121" #应用密钥
  templateId: "5092"



